### ISSUE TITLE
directly attach background images to plotly figures 

### ISSUE THREAD

**Issue by KawanaReeves** [snakesonabrain/groundhog#24]
for plots with background Image(s) (f.e. plot_robertson_ chart). Attach pictures directly to the plotly figure rather than accessing it via a local filepath. That way plots can be uploaded to online libraries (f.e. Chart Studio etc.) and are in general less dependant.
Solution proposal:
opening the image as a PIL.Image.Image object (this requires the pillow package) and passing that image object as the image source property. This will convert the image into a base64 encoded string and embed it in the figure so that it no longer depends on the file on the filesystem.
greyed out original code vs. suggested code below:
![robertson_chart_code](https://user-images.githubusercontent.com/101801768/159677333-a76f9901-2909-40ad-a998-53c6e6a0cfc3.png)
note that the package dependency needs to be amended

**Comment by snakesonabrain** [comment]
@KawanaReeves I finally managed to resolve this one. The changes are in DEV

**Comment by snakesonabrain** [comment]
Closing after running pipelines successfully.
