### ISSUE TITLE
shallowfoundation stressdistribution

### ISSUE THREAD

**Issue by KawanaReeves** [snakesonabrain/groundhog#26]
in shallowfoundation.stressdistribution line 179:

the code should be changed to the absolute value of alpha. Without the absolute value, the stress increase below any point of the foundation is zero. Otherwise stress distribution can only be determined next to the rightmost foundation corner

![Screenshot_settlement](https://user-images.githubusercontent.com/101801768/168256509-036eea11-b440-4747-b749-e87d30323d5e.PNG)

**Comment by snakesonabrain** [comment]
Indeed, I spotted that a couple of days ago and corrected it. The change is already on the DEV branch. Wrote some additional unit tests for this.
