### ISSUE TITLE
Design or Characteristic capacity of shallow foundations

### ISSUE THREAD

**Issue by KawanaReeves** [snakesonabrain/groundhog#27]
I was wondering whether the results for vertical and sliding capacity of the shallowfoundation function verticalcapacity_(un)drained_api are Design or characteristic Values? The docstrings suggest a design value, but I dont see the partial safety factors gamma_m as mentioned in the API reference document. So far safety factors are only used for the calculate_envelope function.

**Comment by snakesonabrain** [comment]
The values for the individual functions are characteristic values. You can apply factors by creating a `ShallowFoundationCapacityUndrained` or `ShallowFoundationCapacityDrained` object and applying the method `calculate_envelope`. This method has arguments `factor_sliding=1.5` and `factor_bearing=2`.

Here's an example with factors for bearing and sliding increased to 3 and 2 respectively.

`from groundhog.shallowfoundations.capacity import ShallowFoundationCapacityUndrained`
`analysis = ShallowFoundationCapacityUndrained(title='Undrained capacity')`
`analysis.set_geometry(length=8, width=5, depth=0, skirted=False)`
`analysis.set_soilparameters_undrained(unit_weight=15, su_base=10, su_increase=1)`
`analysis.set_eccentricity(eccentricity_width=0, eccentricity_length=0)`
`analysis.calculate_envelope(factor_bearing=3, factor_sliding=2)`
`plot = analysis.plot_envelope()`

**Comment by KawanaReeves** [comment]
yeah I figured the calculate_envelope function uses the safety factors. I was just wondering, since the formula for capacity suggests a design value but the actual calculation omits the safety factors. I wasn't sure if groundhog, somewhere in the background, already implicitly transforms the characteristic values into design ones. 
It's clear now. Thanks for your super fast reply. Much appreciated.

**Comment by snakesonabrain** [comment]
groundhog never does something implicitly 😉. The goal of the package is to reveal all the steps, either through the docs or at the very least through the open-source code.
You can of course use the function with factored material parameters but the API/ISO standard suggests using factors on the calculated resistances (vertical and horizontal).
The current approach allows flexibility in where you want to apply the factors.
