### ISSUE TITLE
Numpy 2.0 and groundhog

### ISSUE THREAD

**Issue by Mussie83** [snakesonabrain/groundhog#46]
I have just switched to a new NumPy version and have after that tried to use the groundhog library. 

Are there any reported issues on this case similar to mine (see error message below)? 

Error: np.NaN was removed in the NumPy 2.0 release. Use np.nan instead.

Changing the parts of the gorundhog library to "np.nan" might be a way foreward for now, but I dont know wether there might also be other issues.

**Comment by snakesonabrain** [comment]
The current version of DEV has a requirements.txt file which has been updated to include Numpy >= 2.0. All code and unit tests have been modified to run with this version.
I would recommend creating a virtual environment for running groundhog and install dependencies from the requirements.txt and optional-requirements.txt file. This can be done with venv or with conda.
