### ISSUE TITLE
Trouble installing pandas==0.24.2 with Python==3.8.5

### ISSUE THREAD

**Issue by asitha-sena** [snakesonabrain/groundhog#7]
@brunostuyts 
Hi Bruno,
I tried to install groundhog with all dependencies in the requirements.txt in a new Python 3.8.5 environment. 
`pip install -r requirements.txt`
But I kept getting a Cython related error as pip tried to build the pandas 0.24.2 wheel. 
![image](https://user-images.githubusercontent.com/8764587/102030731-d810fe80-3d81-11eb-97d2-0c177cf7c8dd.png)

Installing Cython didn't help and just gave a gcc failed error. Not sure why but found a few workarounds:
1. `pip install -U -r requirements.txt` worked since it installed the latest version of each package.
2. Remove pandas==0.24.2 from requirements.txt and install it from conda-forge which has a pre-built wheel
    `conda install -c conda-forge pandas=0.24.2`
3. Change to a Python 3.7.9 environment

However, the best solution in my opinion is to update the requirements.txt file to include pandas>=1.0.0. I ran all the unit tests with pandas=1.1.5 and everything passed (albeit with other warnings). Hope this is helpful feedback :)

**Comment by snakesonabrain** [comment]
Many thanks for highlighting this! 

Added pandas>=1.0.0 to requirements.txt. This change is committed in DEV and will be merged with the master branch for version v0.4.0
