### ISSUE TITLE
Dependency: jinja2 not in requirements.txt

### ISSUE THREAD

**Issue by asitha-sena** [snakesonabrain/groundhog#8]
Suggest adding **jinja2** to requirements.txt as it is needed for several tests.
![image](https://user-images.githubusercontent.com/8764587/102036487-f2060d80-3d90-11eb-91ac-ebb4f2800e4e.png)

I added **jupyterlab** to requirements.txt in my installation and it installed jinja2 as part of the dependency tree.

**Comment by snakesonabrain** [comment]
Added jinja>=2.0.0 to requirements.txt. This change is committed in DEV and will be merged with the master branch for version v0.4.0
